In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("C:\\TRJ\\programming\\projects\\ml\\sentry\\Sentry_app\\ml\\datasets\\raw\\crime\\crime_delhi.csv")
district = pd.read_csv("../datasets\\raw\\crime\\delhi_ps_district_mapping.csv")
district['Police_Station_Area'] = district['Police_Station_Area'].str.strip().str.lower()

In [24]:
df = df.merge(
    district, 
    left_on="nm_pol",
    right_on = "Police_Station_Area",
    how="left",
)

In [25]:
df = df.drop(columns=['Police_Station_Area'])

In [26]:
df

,nm_pol,murder,rape,gangrape,robbery,theft,assualt murders,sexual harassement,totarea,totalcrime,long,lat,crime/area,area,District
0,chitranjan park (cr park),2,6,1,35,442,19,7,2659329.537,512,77.24920,28.53632,192.529731,2.659330,SOUTH
1,dabri,8,28,0,79,240,26,16,3401013.428,397,77.08600,28.61268,116.729912,3.401013,DWARKA
2,malviya nagar,3,28,1,33,694,63,15,1379853.572,837,77.20418,28.52989,606.586102,1.379854,SOUTH
3,chandni mahal,1,8,1,23,529,19,7,5570696.132,588,77.23608,28.64361,105.552338,5.570696,CENTRAL
4,model town,0,4,1,45,393,9,14,2689157.085,466,77.19369,28.70257,173.288501,2.689157,NORTH WEST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,gtb enclave,1,1,0,13,86,6,7,2874304.374,114,77.31600,28.68496,39.661770,2.874304,EAST
162,new usmanpur,0,8,1,10,580,9,5,3093393.387,613,77.26207,28.67202,198.164256,3.093393,NORTH EAST
163,sonia vihar,6,25,1,25,300,42,8,4453887.398,407,77.25611,28.71128,91.380846,4.453887,NORTH EAST
164,karawal nagar,7,15,2,26,334,19,7,2937546.578,410,77.27450,28.73284,139.572255,2.937547,NORTH EAST
165,gokalpuri,2,6,2,22,306,19,8,1566343.791,365,77.28085,28.70225,233.026748,1.566344,NORTH EAST

In [27]:
df.head()

,nm_pol,murder,rape,gangrape,robbery,theft,assualt murders,sexual harassement,totarea,totalcrime,long,lat,crime/area,area,District
0,chitranjan park (cr park),2,6,1,35,442,19,7,2659329.537,512,77.24920,28.53632,192.529731,2.659330,SOUTH
1,dabri,8,28,0,79,240,26,16,3401013.428,397,77.08600,28.61268,116.729912,3.401013,DWARKA
2,malviya nagar,3,28,1,33,694,63,15,1379853.572,837,77.20418,28.52989,606.586102,1.379854,SOUTH
3,chandni mahal,1,8,1,23,529,19,7,5570696.132,588,77.23608,28.64361,105.552338,5.570696,CENTRAL
4,model town,0,4,1,45,393,9,14,2689157.085,466,77.19369,28.70257,173.288501,2.689157,NORTH WEST

In [28]:
df.describe()

,murder,rape,gangrape,robbery,theft,assualt murders,sexual harassement,totarea,totalcrime,long,lat,crime/area,area
count,166.000000,166.000000,166.000000,166.000000,166.000000,166.000000,166.000000,1.660000e+02,166.000000,166.000000,166.000000,166.000000,166.000000
mean,3.481928,11.765060,0.933735,34.259036,400.012048,18.957831,9.469880,7.453897e+06,478.879518,77.186804,28.641116,166.570299,7.453897
std,2.819247,7.736508,1.216730,24.730286,223.540600,13.101632,7.225103,1.160207e+07,251.008555,0.087788,0.066989,143.514109,11.602075
min,0.000000,0.000000,0.000000,1.000000,41.000000,1.000000,0.000000,8.784528e+05,62.000000,76.915550,28.465490,4.395489,0.878453
25%,1.000000,6.000000,0.000000,16.250000,244.250000,9.000000,4.000000,1.955090e+06,295.250000,77.121842,28.598382,54.204542,1.955090
50%,3.000000,10.500000,1.000000,28.000000,371.000000,17.000000,8.000000,2.975209e+06,461.000000,77.202950,28.647675,135.776292,2.975209
75%,5.750000,16.000000,1.000000,46.000000,505.750000,24.000000,12.750000,6.082123e+06,616.000000,77.256358,28.684777,230.131065,6.082123
max,10.000000,43.000000,6.000000,126.000000,1273.000000,68.000000,40.000000,7.046949e+07,1433.000000,77.332670,28.853210,792.025514,70.469487

In [29]:
df.columns

Index(['nm_pol', 'murder', 'rape', 'gangrape', 'robbery', 'theft',
       'assualt murders', 'sexual harassement', 'totarea', 'totalcrime',
       'long', 'lat', 'crime/area', 'area', 'District'],
      dtype='object')

In [30]:
if "crime/area" not in df.columns:
    df["crime_per_area"] = df["totalcrime"] / (df["area"] + 1e-8)
else:
    df["crime_per_area"] = df["crime/area"]

In [31]:
df.head()

,nm_pol,murder,rape,gangrape,robbery,theft,assualt murders,sexual harassement,totarea,totalcrime,long,lat,crime/area,area,District,crime_per_area
0,chitranjan park (cr park),2,6,1,35,442,19,7,2659329.537,512,77.24920,28.53632,192.529731,2.659330,SOUTH,192.529731
1,dabri,8,28,0,79,240,26,16,3401013.428,397,77.08600,28.61268,116.729912,3.401013,DWARKA,116.729912
2,malviya nagar,3,28,1,33,694,63,15,1379853.572,837,77.20418,28.52989,606.586102,1.379854,SOUTH,606.586102
3,chandni mahal,1,8,1,23,529,19,7,5570696.132,588,77.23608,28.64361,105.552338,5.570696,CENTRAL,105.552338
4,model town,0,4,1,45,393,9,14,2689157.085,466,77.19369,28.70257,173.288501,2.689157,NORTH WEST,173.288501

In [32]:
df["nm_pol"] = df["nm_pol"].str.strip().str.upper()

df = df[[
    "nm_pol",
    "totalcrime",
    "crime_per_area",
    "murder",
    "rape",
    "robbery",
    "theft",
    "District"
]]

In [33]:
len(df['nm_pol'].unique())

157

In [34]:
df.head()

,nm_pol,totalcrime,crime_per_area,murder,rape,robbery,theft,District
0,CHITRANJAN PARK (CR PARK),512,192.529731,2,6,35,442,SOUTH
1,DABRI,397,116.729912,8,28,79,240,DWARKA
2,MALVIYA NAGAR,837,606.586102,3,28,33,694,SOUTH
3,CHANDNI MAHAL,588,105.552338,1,8,23,529,CENTRAL
4,MODEL TOWN,466,173.288501,0,4,45,393,NORTH WEST

In [ ]:
df.to_csv("C:\\TRJ\\programming\\projects\\ml\\sentry\\Sentry_app\\ml\\datasets\\processed\\crime/crime_processed.csv", index=False)