In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../datasets/accident/delhi_accident_data.csv")

In [4]:
df.head()

,S.No.,Traffic_Districts,Fatal_2015,Fatal_2016,Fatal_2017,Fatal_2018,Fatal_2019,Injury_2015,Injury_2016,Injury_2017,...,NonInjury_2015,NonInjury_2016,NonInjury_2017,NonInjury_2018,NonInjury_2019,Total_2015,Total_2016,Total_2017,Total_2018,Total_2019
0,1,CENTRAL,64,55,55,58,50,264,207,184,...,6,7,6,4,2,334,269,245,219,188
1,2,DWARKA,0,0,0,112,69,0,0,0,...,0,0,0,6,6,0,0,0,372,315
2,3,NEW DELHI,60,57,65,69,43,206,191,176,...,21,17,13,6,8,287,265,254,224,179
3,4,EAST,130,96,131,132,132,643,581,462,...,26,17,14,8,8,799,694,607,547,433
4,5,NORTH EAST,115,100,91,126,113,548,511,468,...,2,1,1,3,2,665,612,560,571,487

In [5]:
df['Traffic_Districts'].unique()

<StringArray>
[   'CENTRAL',     'DWARKA',  'NEW DELHI',       'EAST', 'NORTH EAST',
 'NORTH WEST',      'NORTH',      'OUTER',      'SOUTH', 'SOUTH-EAST',
 'SOUTH WEST',       'WEST']
Length: 12, dtype: str

In [6]:
df.columns

Index(['S.No.', 'Traffic_Districts', 'Fatal_2015', 'Fatal_2016', 'Fatal_2017',
       'Fatal_2018', 'Fatal_2019', 'Injury_2015', 'Injury_2016', 'Injury_2017',
       'Injury_2018', 'Injury_2019', 'NonInjury_2015', 'NonInjury_2016',
       'NonInjury_2017', 'NonInjury_2018', 'NonInjury_2019', 'Total_2015',
       'Total_2016', 'Total_2017', 'Total_2018', 'Total_2019'],
      dtype='str')

In [7]:
years = [2018, 2019]
records = []

for _, row in df.iterrows():
    for year in years:
        records.append({
            "Traffic_Districts": row["Traffic_Districts"],
            "Year": year,
            "Fatal_count": row[f"Fatal_{year}"],
            "Injury_count": row[f"Injury_{year}"]
        })

traffic_df = pd.DataFrame(records)

In [8]:
traffic_df

   Traffic_Districts  Year  Fatal_count  Injury_count
0            CENTRAL  2018           58           157
1            CENTRAL  2019           50           136
2             DWARKA  2018          112           254
3             DWARKA  2019           69           240
4          NEW DELHI  2018           69           149
5          NEW DELHI  2019           43           128
6               EAST  2018          132           407
7               EAST  2019          132           293
8         NORTH EAST  2018          126           442
9         NORTH EAST  2019          113           372
10        NORTH WEST  2018          265           535
11        NORTH WEST  2019          211           528
12             NORTH  2018          108           295
13             NORTH  2019          123           266
14             OUTER  2018          166           491
15             OUTER  2019          146           453
16             SOUTH  2018          119           510
17             SOUTH  2019          109           393
18        SOUTH-EAST  2018          146           542
19        SOUTH-EAST  2019          155           476
20        SOUTH WEST  2018          108           372
21        SOUTH WEST  2019          106           280
22              WEST  2018          248           629
23              WEST  2019          176           560

In [9]:
OUTPUT_PATH = "..\\datasets\\accident\\accident_processed.csv"

traffic_df.to_csv(OUTPUT_PATH, index=False)