In [261]:
import pandas as pd

CRIME = "..\\datasets\\processed\\crime\\crime_processed.csv"
ACCIDENT = "..\\datasets\\processed\\accident\\accident_processed.csv"
SAFETIPIN = "..\\datasets\\processed\\safetipin\\safetipin_processed.csv"
AQI = "..\\datasets\\processed\\aqi\\aqi_processed.csv"
WEATHER = "..\\datasets\\processed\\weather\\weather_processed.csv"

OUTPUT = "..\\datasets\\processed/final_dataset.csv"

crime = pd.read_csv(CRIME)
accident = pd.read_csv(ACCIDENT)
safetipin = pd.read_csv(SAFETIPIN)
aqi = pd.read_csv(AQI, parse_dates=["Date"])
weather = pd.read_csv(WEATHER, parse_dates=["Date"])

In [262]:
full_df = crime.merge(
    accident, 
    left_on='District',
    right_on='Traffic_Districts',
    how='left' 
)

In [263]:
full_df = full_df.merge(
    safetipin,
    left_on="nm_pol",
    right_on="Police_Station",
    how="left"
)

In [264]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

full_df[['Safety Score']] = imputer.fit_transform(full_df[['Safety Score']])

In [265]:
full_df.sample(8)

,nm_pol,totalcrime,crime_per_area,murder,rape,robbery,theft,District,Traffic_Districts,avg_total_accidents,Police_Station,Safety Score,Lighting,Visibility,Openness,Security
93,HAUZ QAZI,491,158.597452,1,6,12,431,CENTRAL,CENTRAL,251.0,HAUZ QAZI,3.5,2.6,0.8,2.2,0.4
105,SAKET,134,49.031343,2,0,2,126,SOUTH,SOUTH,619.2,SAKET,3.3,2.5,0.8,2.0,0.3
1,DABRI,397,116.729912,8,28,79,240,DWARKA,DWARKA,137.4,DABRI,2.9,2.0,0.9,2.1,0.4
158,ROHTAS NAGAR,312,185.200000,2,8,15,287,EAST,EAST,616.0,ROHTAS NAGAR,3.7,2.7,1.6,2.1,0.3
116,KHYALA,793,378.869332,5,18,30,663,WEST,WEST,861.4,KHYALA,4.0,2.4,1.9,2.0,1.0
125,NIHAL VIHAR,509,139.070635,1,6,39,437,OUTER,OUTER,661.4,NIHAL VIHAR,4.1,2.8,1.9,2.0,0.9
67,HARI NAGAR,528,221.275888,5,17,11,469,WEST,WEST,861.4,HARI NAGAR,4.0,2.8,1.7,2.0,0.9
55,H. N. DIN,257,24.912023,1,8,15,214,SOUTH-EAST,SOUTH-EAST,960.2,H. N. DIN,3.6,2.5,1.3,2.1,0.5

In [266]:
weather.isna().sum()

Date                   0
Avg Temperature        0
Avg Humidity           0
Total Precipitation    0
dtype: int64

In [267]:
date_df = aqi.merge(
    weather,
    on="Date",
    how="inner"
)

In [268]:
date_df.describe()

,Date,AQI,Avg Temperature,Avg Humidity,Total Precipitation
count,113428,113428.000000,113428.000000,113428.000000,113428.000000
mean,2019-01-14 18:13:40.368868,238.348494,25.641528,60.469941,0.144112
min,2018-01-01 00:00:00,21.000000,6.610000,12.900000,0.000000
25%,2018-07-26 00:00:00,135.000000,19.440000,48.100000,0.000000
50%,2019-01-18 00:00:00,225.000000,27.440000,62.000000,0.000000
75%,2019-07-11 00:00:00,322.000000,31.500000,73.700000,0.040000
max,2019-12-31 00:00:00,1019.000000,39.890000,100.000000,5.660000
std,NaN,126.013965,7.614654,19.232280,0.512968

In [269]:

full_df = date_df.merge(
    full_df,
    left_on="Police_Station_Areas",
    right_on="nm_pol",
    how="inner"
)

In [270]:
full_df

,Police_Station_Areas,Date,AQI,Avg Temperature,Avg Humidity,Total Precipitation,nm_pol,totalcrime,crime_per_area,murder,...,theft,District,Traffic_Districts,avg_total_accidents,Police_Station,Safety Score,Lighting,Visibility,Openness,Security
0,ADARSH NAGAR,2018-01-01,359.0,12.94,81.6,0.00,ADARSH NAGAR,434,263.638985,3,...,354,NORTH WEST,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3
1,ADARSH NAGAR,2018-01-02,333.0,11.78,85.0,0.11,ADARSH NAGAR,434,263.638985,3,...,354,NORTH WEST,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3
2,ADARSH NAGAR,2018-01-03,322.0,10.50,87.3,0.00,ADARSH NAGAR,434,263.638985,3,...,354,NORTH WEST,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3
3,ADARSH NAGAR,2018-01-04,344.0,11.06,85.2,0.00,ADARSH NAGAR,434,263.638985,3,...,354,NORTH WEST,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3
4,ADARSH NAGAR,2018-01-05,330.0,11.61,80.8,0.00,ADARSH NAGAR,434,263.638985,3,...,354,NORTH WEST,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113423,WELCOME,2019-12-27,380.0,8.39,86.6,0.00,WELCOME,364,201.603478,0,...,337,NORTH EAST,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3
113424,WELCOME,2019-12-28,443.0,7.06,95.9,0.00,WELCOME,364,201.603478,0,...,337,NORTH EAST,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3
113425,WELCOME,2019-12-29,501.0,8.61,91.0,0.00,WELCOME,364,201.603478,0,...,337,NORTH EAST,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3
113426,WELCOME,2019-12-30,595.0,6.61,98.9,0.00,WELCOME,364,201.603478,0,...,337,NORTH EAST,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3
113427,WELCOME,2019-12-31,393.0,10.67,73.1,0.00,WELCOME,364,201.603478,0,...,337,NORTH EAST,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3

In [271]:
full_df.columns

Index(['Police_Station_Areas', 'Date', 'AQI', 'Avg Temperature',
       'Avg Humidity', 'Total Precipitation', 'nm_pol', 'totalcrime',
       'crime_per_area', 'murder', 'rape', 'robbery', 'theft', 'District',
       'Traffic_Districts', 'avg_total_accidents', 'Police_Station',
       'Safety Score', 'Lighting', 'Visibility', 'Openness', 'Security'],
      dtype='str')

In [272]:
def distribute_date(df, date_col):
    df[date_col] = pd.to_datetime(df[date_col])
    df['day'] = df[date_col].dt.day
    df['month'] = df[date_col].dt.month
    return df

distribute_date(full_df,'Date')

,Police_Station_Areas,Date,AQI,Avg Temperature,Avg Humidity,Total Precipitation,nm_pol,totalcrime,crime_per_area,murder,...,Traffic_Districts,avg_total_accidents,Police_Station,Safety Score,Lighting,Visibility,Openness,Security,day,month
0,ADARSH NAGAR,2018-01-01,359.0,12.94,81.6,0.00,ADARSH NAGAR,434,263.638985,3,...,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3,1,1
1,ADARSH NAGAR,2018-01-02,333.0,11.78,85.0,0.11,ADARSH NAGAR,434,263.638985,3,...,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3,2,1
2,ADARSH NAGAR,2018-01-03,322.0,10.50,87.3,0.00,ADARSH NAGAR,434,263.638985,3,...,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3,3,1
3,ADARSH NAGAR,2018-01-04,344.0,11.06,85.2,0.00,ADARSH NAGAR,434,263.638985,3,...,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3,4,1
4,ADARSH NAGAR,2018-01-05,330.0,11.61,80.8,0.00,ADARSH NAGAR,434,263.638985,3,...,NORTH WEST,894.2,ADARSH NAGAR,3.3,2.6,0.9,2.2,0.3,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113423,WELCOME,2019-12-27,380.0,8.39,86.6,0.00,WELCOME,364,201.603478,0,...,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3,27,12
113424,WELCOME,2019-12-28,443.0,7.06,95.9,0.00,WELCOME,364,201.603478,0,...,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3,28,12
113425,WELCOME,2019-12-29,501.0,8.61,91.0,0.00,WELCOME,364,201.603478,0,...,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3,29,12
113426,WELCOME,2019-12-30,595.0,6.61,98.9,0.00,WELCOME,364,201.603478,0,...,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3,30,12
113427,WELCOME,2019-12-31,393.0,10.67,73.1,0.00,WELCOME,364,201.603478,0,...,NORTH EAST,579.0,WELCOME,3.8,2.6,1.4,2.1,0.3,31,12

In [273]:
full_df = full_df.drop(columns=['nm_pol', 'District','Police_Station', 'Date'])

In [274]:
full_df

,Police_Station_Areas,AQI,Avg Temperature,Avg Humidity,Total Precipitation,totalcrime,crime_per_area,murder,rape,robbery,theft,Traffic_Districts,avg_total_accidents,Safety Score,Lighting,Visibility,Openness,Security,day,month
0,ADARSH NAGAR,359.0,12.94,81.6,0.00,434,263.638985,3,15,41,354,NORTH WEST,894.2,3.3,2.6,0.9,2.2,0.3,1,1
1,ADARSH NAGAR,333.0,11.78,85.0,0.11,434,263.638985,3,15,41,354,NORTH WEST,894.2,3.3,2.6,0.9,2.2,0.3,2,1
2,ADARSH NAGAR,322.0,10.50,87.3,0.00,434,263.638985,3,15,41,354,NORTH WEST,894.2,3.3,2.6,0.9,2.2,0.3,3,1
3,ADARSH NAGAR,344.0,11.06,85.2,0.00,434,263.638985,3,15,41,354,NORTH WEST,894.2,3.3,2.6,0.9,2.2,0.3,4,1
4,ADARSH NAGAR,330.0,11.61,80.8,0.00,434,263.638985,3,15,41,354,NORTH WEST,894.2,3.3,2.6,0.9,2.2,0.3,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113423,WELCOME,380.0,8.39,86.6,0.00,364,201.603478,0,2,15,337,NORTH EAST,579.0,3.8,2.6,1.4,2.1,0.3,27,12
113424,WELCOME,443.0,7.06,95.9,0.00,364,201.603478,0,2,15,337,NORTH EAST,579.0,3.8,2.6,1.4,2.1,0.3,28,12
113425,WELCOME,501.0,8.61,91.0,0.00,364,201.603478,0,2,15,337,NORTH EAST,579.0,3.8,2.6,1.4,2.1,0.3,29,12
113426,WELCOME,595.0,6.61,98.9,0.00,364,201.603478,0,2,15,337,NORTH EAST,579.0,3.8,2.6,1.4,2.1,0.3,30,12
113427,WELCOME,393.0,10.67,73.1,0.00,364,201.603478,0,2,15,337,NORTH EAST,579.0,3.8,2.6,1.4,2.1,0.3,31,12

In [275]:
full_df.to_csv(OUTPUT, index=False)